### ISSUE TITLE
Inavlid entries

### ISSUE THREAD

**Issue by DTX3** [TheCSMods/mc-tcdcommons#17]
### Question

I get the following error/warning in our logs.

[ForkJoinPool-1-worker-15/WARN]: The mod "tcdcommons" contains invalid entries in its mod json:
- Unsupported root entry "" at line 27 column 4
- Unsupported root entry "" at line 27 column 198
- Unsupported root entry "" at line 29 column 4
- Unsupported root entry "" at line 29 column 24

Is this anything to worry about?

Version: tcdcommons-3.12.3+fabric-1.20.1

**Comment by TheCSDev** [comment]
Hello!  
No worries, there is nothing to worry about, as it is completely harmless.  
If you'd like to read more about this, feel free to go visit https://github.com/TheCSMods/mc-better-stats/issues/122
